//
//  ConversationsRouter.swift
//  vkExtended
//
//  Created Ярослав Стрельников on 20.10.2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MaterialComponents

class ConversationsRouter: ConversationsWireframeProtocol {
    
    weak var viewController: UIViewController?
    weak var baseViewController: UIViewController?
    var transitioningDelegate = MDCBottomDrawerTransitionController()
    
    // Инициализация VIPER модуля
    static func initModule(_ viewController: ConversationsViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = ConversationsInteractor()
        let router = ConversationsRouter()
        let presenter = ConversationsPresenter(interface: viewController, interactor: interactor, router: router)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = viewController
        presenter.interactor = interactor
        router.baseViewController = viewController
    }
    
//    // Открыть чат
//    func openConversation(from conversation: Conversation) {
//        let chatViewController = ChatNewViewController(conversation: conversation)
//        chatViewController.hidesBottomBarWhenPushed = true
//        self.baseViewController?.navigationController?.pushViewController(chatViewController, animated: true)
//    }
    
    // Открыть профиль чата
    func openProfile(userId: Int) {
        self.baseViewController?.navigationController?.pushViewController(ProfileViewController(userId: userId), animated: true)
    }
    
    // Открыть приватные переписки
    func openPrivateConversations() {
        let contentViewController = PrivateConversationsViewController()
        let bottomDrawerViewController = MDCBottomDrawerViewController()
        bottomDrawerViewController.contentViewController = contentViewController
        bottomDrawerViewController.transitioningDelegate = transitioningDelegate
        bottomDrawerViewController.modalPresentationStyle = .custom
        bottomDrawerViewController.trackingScrollView = contentViewController.mainTable
        baseViewController?.navigationController?.present(bottomDrawerViewController, animated: true, completion: nil)
    }
}
