//
//  MenuViewController.swift
//  vkExtended
//
//  Created Ярослав Стрельников on 15.11.2020.
//  Copyright © 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Material

class MenuViewController: BaseViewController, MenuViewProtocol {

	var presenter: MenuPresenterProtocol?
    private let mainTable = TableView(frame: .zero, style: .grouped)
    private let titles: [String] = ["Контент", "Личное", "Настройки", ""]
    private let items: [[String]] = [["Музыка", "Сообщества", "Видео"], ["Файлы", "Закладки", "Понравившееся"], ["Интерфейс", "Сообщения", "Новости"], ["Выйти из аккаунта"]]
    private let imagesString: [[String]] = [["music_outline_28", "users_3_outline_28", "video_outline_28"], ["document_outline_28", "favorite_outline_28", "like_outline_28"], ["palette_outline_28", "messages_outline_28 @ chats", "news"], ["cancel_outline_28"]]

	override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Меню"
        prepareTable()
        setupTable()
    }

    // Подготовка таблицы
    func prepareTable() {
        view.addSubview(mainTable)
        mainTable.separatorStyle = .none
        mainTable.autoPinEdge(toSuperviewSafeArea: .top, withInset: 56)
        mainTable.autoPinEdge(.bottom, to: .bottom, of: view, withOffset: -(tabBarController?.tabBar.bounds.height ?? 0))
        mainTable.autoPinEdge(.trailing, to: .trailing, of: view)
        mainTable.autoPinEdge(.leading, to: .leading, of: view)
        mainTable.backgroundColor = .adaptableWhite
    }
    
    // Настройка таблицы
    func setupTable() {
        mainTable.keyboardDismissMode = .onDrag
        mainTable.allowsMultipleSelection = false
        mainTable.allowsMultipleSelectionDuringEditing = true
        mainTable.separatorStyle = .none
        mainTable.delegate = self
        mainTable.dataSource = self
        mainTable.register(UINib(nibName: "MenuTableViewCell", bundle: nil), forCellReuseIdentifier: "MenuTableViewCell")
    }
}
extension MenuViewController: UITableViewDelegate, UITableViewDataSource {
    public func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return items[section].count
    }
    
    public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MenuTableViewCell", for: indexPath) as! MenuTableViewCell
        cell.selectionStyle = .none
        cell.itemTitle = items[indexPath.section][indexPath.row]
        cell.itemImage = UIImage(named: imagesString[indexPath.section][indexPath.row])
        cell.itemImageTint = indexPath.section == titles.count - 1 ? .extendedRed : .systemBlue
        cell.itemTitleTint = indexPath.section == titles.count - 1 ? .extendedRed : .getThemeableColor(from: .black)
        return cell
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let header = TableHeader(frame: CGRect(origin: .zero, size: .custom(tableView.bounds.width, section == titles.count - 1 ? 1 : 36)))
        header.headerTitle = titles[section].uppercased()
        header.dividerVisibility = section == 0 ? .invisible : .visible
        return header
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return section == titles.count - 1 ? 1 : 36
    }
    
    public func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 56
    }
    
    public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: false)
    }
    
    public func numberOfSections(in tableView: UITableView) -> Int {
        return titles.count
    }
}
